server:
  port: 8081
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
  mvc:
    static-path-pattern: /static/**
  application:
    name: hanmo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hanmo?useSSL=false&serverTimezone=UTC
    username: root
    password: Gg1936279628
  redis:
    host: localhost
    port: 6379
    #password: Gg1936279628
    lettuce:
      pool:
       max-active: 10
       max-idle: 10
       min-idle: 1
       time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON?????????
mybatis-plus:
  type-aliases-package: com.example.entity # ?????
logging:
  level:
    com.example: debug

